---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-nats
  namespace: default
spec:
  chart:
    spec:
      chart: nats
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nats
      version: 0.17.5
  interval: 10m0s

