apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kuber-parts-proj
  namespace: project
spec:
  sourceRef:
    kind: GitRepository
    name: kuber-parts
  interval: 1m
  path: ./Project/manifests/default/kustomization.yaml # Path tells where to find the files. Excellent for "monorepos" where you have multiple different applications in one repository, like the example repository.
  prune: true # This will make sure that deleting the file will delete the resource
  validation: client # Who validates the objects. Server or the client.
  decryption:
    provider: sops
    secretRef:
      name: sops-age